# Generated by Django 4.2.1 on 2023-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "postid",
                    models.AutoField(
                        db_column="post_id", primary_key=True, serialize=False
                    ),
                ),
                ("userid", models.IntegerField()),
                ("postcontext", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "userid",
                    models.AutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=32)),
            ],
        ),
    ]
